config/routes.rb
Rails.application.routes.draw do

  post '/rate' => 'rater#create', :as => 'rate'
  root 'front_end#index'

  get 'admin' => 'admin/users#index'
  namespace :admin do
    resources :books, path: 'books'
    resources :categories, path: 'categories'
    resources :tags, path: 'tags'
    resources :posts, path: 'posts'
    resources :users, path: 'users', only: [:index, :create, :show, :edit, :update, :destroy]
    resources :reviews, path: 'reviews', only: [:index, :show, :destroy]
  end

  get '/sign-up' => 'admin/users#new'
  get '/sign-in' => 'sessions#view_sign_in'
  post '/sign-in' => 'sessions#create'
  get '/sign-out' => 'sessions#destroy'
  
  # get 'post/:slug' => 'front_end#show_item', as: 'post'
  get 'category/:slug' => 'front_end#category', as: 'category'
  get 'tag/:slug' => 'front_end#tag', as: 'tag'
  get 'books/:slug' => 'front_end#show_book', as: 'book'
  get 'books' => 'front_end#all_book', as: 'books'
  get 'book/autocomplete' => 'front_end#autocomplete', as: 'autocomplete'
  get 'book/search_book' => 'front_end#search_book', as: 'search_book'
  post 'book/check_in_book' => 'front_end#check_in_book', as: 'check_in_book'

  # get 'profile' => 'user#show_user', as: 'profile_user'
  # post 'profile/update' => 'user#update_user', as: 'profile_user_update'

  resources :users ,param: :username do
    member do
      get 'read_books'
    end
  end
  resources :comments, only: [:create, :destroy]
  resources :reviews, only: [:create, :destroy, :update]
  # resources :books, only: [:index, :show]
end

app/models/book.rb
class Book < ActiveRecord::Base
	belongs_to :user, foreign_key: 'created_by'

	has_many :categories, :through => :categories_books
	has_many :categories_books, dependent: :destroy
	
	has_many :tags, :through => :tags_books
	has_many :tags_books, dependent: :destroy
	
	has_many :users, :through => :user_book
	has_many :user_book, dependent: :destroy
	
	has_many :reviews

	mount_uploader :img_path, ImageUploader
	# searchkick autocomplete: ['title']
	
	ratyrate_rateable "quality"
	scope :with_ratings, ->{includes(:rate_average_without_dimension).order("rating_caches.avg desc")}
	
	def self.get_all_books()
		Book.all.order(created_at: :desc)
	end

	def self.get_books(book_number)
		Book.all.order(created_at: :desc).take(book_number)
	end

	def self.get_book(book_id)
		book = self.find_by(id: book_id)
	end

	def self.get_book_by_slug(book_slug)
		book = self.find_by(slug: book_slug)
	end

	def self.create_book(data_create)
		book = self.new(data_create)
		book.save ? book : false
	end

	def self.update_book(book_id, data_update)
		book = self.find_by(id: book_id)
		if !book.nil?
			book.update(data_update) ? book : false
		else
			return false
		end
	end

	def self.delete_book(book_id)
		book = self.find_by(id: book_id)
		if !book.nil?
			book.destroy ? true : false
		else
			return false
		end
	end

	def self.search_title(book_title)
		self.where('title LIKE ?', "%#{book_title}%")
	end
end

app/controllers/admin/books_controller.rb
class Admin::BooksController < ApplicationController
	before_action :signed_in_user
	before_action :check_role

	def index
		@books = Book.get_all_books
	end

	def new
		@book = Book.new
		@categories = Category.get_all_categories
		@tags = Tag.get_all_tags
	end

	def edit
		@book = Book.get_book(params[:id])
		@categories = Category.get_all_categories
		@tags = Tag.get_all_tags
	end

	def update
		@book = Book.update_book(params[:id], book_params)
		if @book
			@category_relations = CategoriesBook.where(book_id: @book.id).all
			if !@category_relations.nil?
				@category_relations.each do |relation|
					relation.destroy
				end
			end
			if !params[:categories].nil?
				params[:categories].each do |category|
					CategoriesBook.create(book_id: @book.id, category_id: category)
				end
			end

			@tag_relations = TagsBook.where(book_id: @book.id).all
			if !@tag_relations.nil?
				@tag_relations.each do |relation|
					relation.destroy
				end
			end
			if !params[:tags].nil?
				params[:tags].each do |tag|
					TagsBook.create(book_id: @book.id, tag_id: tag)
				end
			end

			flash[:success] = 'Update successful'
			redirect_to edit_admin_book_path(@book)
		else
			flash[:error] = 'Update failed'
			redirect_to :back
		end
	end

	def create
		# Create slug for book
		book_last = Book.last
		if book_last.nil?
			book_slug = to_slug(book_params[:title])
		else
			book_slug = book_last.id.to_s + '-' + to_slug(book_params[:title])
		end
		data_create = book_params.merge(
			:created_by => session[:user_id],
			:slug =>book_slug
		)

		book = Book.create_book(data_create)

		if book
			if !params[:categories].nil?
				params[:categories].each do |category|
					CategoriesBook.create(book_id: book.id, category_id: category)
				end
			end

			if !params[:tags].nil?
				params[:tags].each do |tag|
					TagsBook.create(book_id: book.id, tag_id: tag)
				end
			end

			flash[:success] = 'Create successful'
			redirect_to edit_admin_book_path(book)
		else
			flash[:error] = 'Create failed'
			redirect_to :back
		end
	end

	def destroy
		delete_result = Book.delete_book(params[:id])
		if delete_result
			flash[:success] = 'Delete successful'
			redirect_to admin_books_path
		else
			flash[:error] = 'Delete failed'
			redirect_to :back
		end
	end

	private
		def book_params
			params.require(:book).permit(:img_path,:title,:author,:description)
		end

end

app/views/admin/books/edit.html.erb
<div class="x_panel">
    <div class="x_title">
        <h2><%= @book.title %></h2>
        <ul class="nav navbar-right panel_toolbox">
            <li class="pull-right"><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
        </ul>
        <div class="clearfix"></div>
    </div>
    <div class="x_content" id="book_content">
        <!-- content starts here -->
        <%= form_for [:admin, @book], html:{'class' => '', 'data-parsley-validate' => ''} do |f| %>
	    	<div class="row">
	    		<div class="col-sm-3">
		    		<div class="form-group img_preview">
			    		<label for="book_img">Bookjacket</label>
			    		<div class="img">
					        <img src="<%= @book.img_path.url.nil? ? '/img/demo.png' : @book.img_path.url %>" class="full_width book_img img-thumbnail">
				        	<button type="button" class="btn btn-default"><i class="fa fa-pencil-square-o"></i></button>
			        	</div>
				    </div>
		        </div>
	    		<div class="col-sm-9">
	    			<div class="form-group">
					    <label for="book_title">Title</label>
					    <%= f.text_field :title, class: 'form-control', placeholder: 'Title', required: 'required' %>
					</div>
	    			<div class="form-group">
					    <label for="book_author">Athor</label>
					    <%= f.text_field :author, class: 'form-control', placeholder: 'Author', required: 'required' %>
					</div>	
	    			<div class="form-group">
	    				<div class="row">
		    				<div class="col-sm-6">
							    <label for="book_author">Categories</label>
						        <select class="form-control select2 select2-hidden-accessible" name="categories[]" multiple data-placeholder="Select category" style="width: 100%;" tabindex="-1" aria-hidden="true">
						          	<% @categories.each do |category| %>
							            <option 
							              value="<%= category.id %>"
							              <% @book.categories.ids.each do |category_selected| %>
							                <% if category_selected == category.id %>
							                  selected="selected"
							                <% end %>
							              <% end %>
							            >
							              <%= category.category %>
							            </option>
							          <% end %>
						        </select>
					    	</div>
		    				<div class="col-sm-6">
							    <label for="book_author">Tags</label>
							    <select class="form-control select2 select2-hidden-accessible" name="tags[]" multiple data-placeholder="Select tag" style="width: 100%;" tabindex="-1" aria-hidden="true">
						          	<% @tags.each do |tag| %>
							            <option
							              value="<%= tag.id %>"
							              <% @book.tags.ids.each do |tag_selected| %>
							                <% if tag_selected == tag.id%>
							                  selected="selected"
							                <% end %>
							              <% end %>  
							            >
							              <%= tag.tag_name %>
							            </option>
							        <% end %>
						        </select>
					    	</div>
	    				</div>
					</div>
	    			<div class="form-group">
					    <label for="book_description">Description</label>
					    <%= f.text_area :description, class: 'form-control', placeholder: 'Description', rows: '8', required: 'required', spellcheck: 'false' %>
					</div>
	    			<div class="form-group hide">
					    <label for="book_img">Bookjacket</label>
					    <%= f.file_field :img_path, accept: 'image/*', id: 'book_img_path'%>
					</div>
	    			<div class="form-group">
	    				<button type="submit" class="btn btn-success">Update</button>
	    				<a type="button" class="btn btn-danger pull-right" data-toggle="modal" data-target=".delete_comfirm"><i class="fa fa-trash"></i> Delete</a>
					</div>
	    		</div>
	    	</div>
		<% end %>
        <!-- content ends here -->
    </div>
</div>
<!-- MODAL DELETE CONFIRM -->
<div class="modal fade delete_comfirm" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">

      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span>
        </button>
        <h4 class="modal-title" id="myModalLabel2">Are you sure delete this?</h4>
      </div>
      <div class="modal-body text-center">
        <button type="button" class="btn btn-default" data-dismiss="modal">No</button>
        <a href="<%= admin_book_path(@book.id) %>" type="button" class="btn btn-success" data-method="delete">Yes, I'm sure</a>
      </div>

    </div>
  </div>
</div><!-- END MODAL -->
<% content_for :add_js do %>
	<script type="text/javascript">
	    $(document).ready(function () {
	    	$('.img_preview div.img').click(function(){
	    		$('#book_img_path').click()
	    	})

	    })
	</script>
<% end %>

<% extends_layout "admin/books/master" %>

app/views/admin/books/index.html.erb
<div class="x_panel">
    <div class="x_title">
        <h2>All books</h2>
        <ul class="nav navbar-right panel_toolbox">
            <li class="pull-right"><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
        </ul>
        <div class="clearfix"></div>
    </div>
    <div class="x_content">
        <!-- content starts here -->
        <table class="table table-striped" id="list-item" cellspacing="0" width="100%">
	        <thead>
	            <tr>
	                <th>Title</th>
	                <th>Author</th>
	                <th>Created By</th>
	                <th width="140px">Created Time</th>
	            </tr>
	        </thead>
	        <tfoot>
	            <tr>
	                <th>Title</th>
	                <th>Author</th>
	                <th>Created By</th>
	                <th>Created Time</th>
	            </tr>
	        </tfoot>
	        <tbody style="text-transform: capitalize;">
	        	<% @books.each do |book|%>
			        <tr>
			        	<td>
			        		<a href="<%= edit_admin_book_path(book) %>" class="text-success"><u><%=book.title%></u></a>
			        	</td>
			        	<td><%=book.author%></td>
			        	<td><%=book.user.username%></td>
			        	<td><%=book.created_at%></td>
			        </tr>
		        <% end %>
	        </tbody>
	    </table>
        <!-- content ends here -->
    </div>
</div>

<% content_for :add_js do %>
	<script type="text/javascript">
	    $(document).ready(function () {
	    	//DataTable
	    	$('#list-item').DataTable();
	    })
	</script>
<% end %>

<% extends_layout "admin/books/master" %>

app/views/admin/books/master.html.erb
<% provide(:title, "HTube | Admin") %>

<% content_for :back_end_main do %>
	<div class="right_col" role="main">
 
	    <div class="">
	        <div class="page-title">
	            <div class="title_left">
	                <h3>
	                    <a href="<%= admin_books_path %>"><u>Books</u></a> 
	                    <a href="<%= new_admin_book_path %>" class="btn btn-xs btn-success"><strong>+</strong> Add new</a>
	                </h3>
	            </div>
	        </div>
	        <div class="clearfix"></div>
	 
	        <div class="row">
	            <div class="col-sm-12">
	                <%= yield %>
	            </div>
	        </div>
	    </div>
	</div>
<% end %>
<% content_for :add_js do %>
	<script type="text/javascript">
	    $(document).ready(function () {
	    	//DataTable
	    	$('#list-item').DataTable();
	    	$(".select2").select2();
	    	
	    	<% if flash[:error] %>
				new PNotify({
	              	title: 'Error',
	              	text: '<%= flash[:error] %>',
	              	type: 'error',
	              	hide: false,
	              	styling: 'bootstrap3'
	          	});
          	<% end %>
	    	<% if flash[:success] %>
				new PNotify({
	              	title: 'Success',
	              	text: '<%= flash[:success] %>',
	              	type: 'success',
	              	delay: 3000,
	              	styling: 'bootstrap3'
	          	});
          	<% end %>
	    })

	    /* Change images before upload */
		$('#book_img_path').on('change',function(){
	        readURL(this,'.book_img'); 
	    })
	    function readURL(input,selector) {
	        if (input.files && input.files[0]) {
	            var reader = new FileReader();
	            reader.onload = function (theFile) {
	                var image = new Image();
	                image.src = theFile.target.result;
	                image.onload = function() {
	                    $(selector).attr('src', this.src);
	             
	                };
	            }
	            reader.readAsDataURL(input.files[0]);
	        }
	    }
	    /* END change image*/
	    
	</script>
<% end %>

<% extends_layout "admin/layouts/master" %>

app/views/admin/books/new.html.erb
<div class="x_panel">
    <div class="x_title">
        <h2>Add new</h2>
        <ul class="nav navbar-right panel_toolbox">
            <li class="pull-right"><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
        </ul>
        <div class="clearfix"></div>
    </div>
    <div class="x_content" id="book_content">
        <!-- content starts here -->
        <%= form_for [:admin, @book], html:{'class' => '', 'data-parsley-validate' => ''} do |f| %>
	    	<div class="row">
	    		<div class="col-sm-3">
		    		<div class="form-group img_preview">
			    		<label for="book_img">Bookjacket</label>
			    		<div class="img">
					        <img src="<%= image_path("chuyenketrangnghe.jpg") %>" class="full_width book_img img-thumbnail">
				        	<button type="button" class="btn btn-default"><i class="fa fa-pencil-square-o"></i></button>
			        	</div>
				    </div>
		        </div>
	    		<div class="col-sm-9">
	    			<div class="form-group">
					    <label for="book_title">Title</label>
					    <%= f.text_field :title, class: 'form-control', placeholder: 'Title', required: 'required' %>
					</div>
	    			<div class="form-group">
					    <label for="book_author">Athor</label>
					    <%= f.text_field :author, class: 'form-control', placeholder: 'Author', required: 'required' %>
					</div>
	    			<div class="form-group">
	    				<div class="row">
		    				<div class="col-sm-6">
							    <label for="book_author">Categories</label>
						        <select class="form-control select2 select2-hidden-accessible" name="categories[]" multiple data-placeholder="Select category" style="width: 100%;" tabindex="-1" aria-hidden="true">
						          	<% @categories.each do |category| %>
						            	<option value="<%= category.id %>"><%= category.category %></option>
						          	<% end %>
						        </select>
					    	</div>
		    				<div class="col-sm-6">
							    <label for="book_author">Tags</label>
							    <select class="form-control select2 select2-hidden-accessible" name="tags[]" multiple data-placeholder="Select tag" style="width: 100%;" tabindex="-1" aria-hidden="true">
						          	<% @tags.each do |tag| %>
						            	<option value="<%= tag.id %>"><%= tag.tag_name %></option>
						          	<% end %>
						        </select>
					    	</div>
	    				</div>
					</div>	
	    			<div class="form-group">
					    <label for="book_description">Description</label>
					    <%= f.text_area :description, class: 'form-control', placeholder: 'Description', rows: '8', required: 'required' %>
					</div>
	    			<div class="form-group hide">
					    <label for="book_img">Bookjacket</label>
					    <%= f.file_field :img_path, accept: 'image/*', id: 'book_img_path'%>
					</div>
	    			<div class="form-group">
	    				<button type="submit" class="btn btn-success">Create</button>
					</div>
	    		</div>
	    	</div>
		<% end %>
        <!-- content ends here -->
    </div>
</div>

<% content_for :add_js do %>
	<script type="text/javascript">
	    $(document).ready(function () {
	    	$('.img_preview div.img').click(function(){
	    		$('#book_img_path').click()
	    	})

	    })

	    /* Change images before upload */
		$('#book_img_path').on('change',function(){
	        readURL(this,'.book_img'); 
	    })
	    function readURL(input,selector) {
	        if (input.files && input.files[0]) {
	            var reader = new FileReader();
	            reader.onload = function (theFile) {
	                var image = new Image();
	                image.src = theFile.target.result;
	                image.onload = function() {
	                    $(selector).attr('src', this.src);
	             
	                };
	            }
	            reader.readAsDataURL(input.files[0]);
	        }
	    }
	    /* END change image*/
	</script>
<% end %>

<% extends_layout "admin/books/master" %>