config/routes.rb
Rails.application.routes.draw do

  post '/rate' => 'rater#create', :as => 'rate'
  root 'front_end#index'

  get 'admin' => 'admin/users#index'
  namespace :admin do
    resources :books, path: 'books'
    resources :categories, path: 'categories'
    resources :tags, path: 'tags'
    resources :posts, path: 'posts'
    resources :users, path: 'users', only: [:index, :create, :show, :edit, :update, :destroy]
    resources :reviews, path: 'reviews', only: [:index, :show, :destroy]
  end

  get '/sign-up' => 'admin/users#new'
  get '/sign-in' => 'sessions#view_sign_in'
  post '/sign-in' => 'sessions#create'
  get '/sign-out' => 'sessions#destroy'
  
  # get 'post/:slug' => 'front_end#show_item', as: 'post'
  get 'category/:slug' => 'front_end#category', as: 'category'
  get 'tag/:slug' => 'front_end#tag', as: 'tag'
  get 'books/:slug' => 'front_end#show_book', as: 'book'
  get 'books' => 'front_end#all_book', as: 'books'
  get 'book/autocomplete' => 'front_end#autocomplete', as: 'autocomplete'
  get 'book/search_book' => 'front_end#search_book', as: 'search_book'
  post 'book/check_in_book' => 'front_end#check_in_book', as: 'check_in_book'

  # get 'profile' => 'user#show_user', as: 'profile_user'
  # post 'profile/update' => 'user#update_user', as: 'profile_user_update'

  resources :users ,param: :username do
    member do
      get 'read_books'
    end
  end
  resources :comments, only: [:create, :destroy]
  resources :reviews, only: [:create, :destroy, :update]
  # resources :books, only: [:index, :show]
end

app/controllers/admin/reviews_controller.rb
class Admin::ReviewsController < ApplicationController
	before_action :signed_in_user, :check_role

    def index
        @reviews = Review.all
    end

    def show
        @review = Review.find(params[:id])
    end

    def destroy
        @review = Review.find(params[:id])
        @review.destroy
        redirect_to admin_reviews_path
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	before_action :signed_in_user, only: [:create, :destroy]

	def create
		@book = Book.find(params[:book_id])
		@review = current_user.reviews.build(review_params)
		@review.book_id = @book.id
	    if @review.save
	      	respond_to do |format|
		        format.html { redirect_to book_path(@book.slug) }
		        format.js
		    end
	    else
	      redirect_to book_path(@book.slug)
	    end
	end
	
	def update
		@book = Book.find(params[:book_id])
		@review = Review.find(params[:id])
		@review.content = review_params[:content]
	    if @review.save
	      	respond_to do |format|
		        format.html { redirect_to book_path(@book.slug) }
		        format.js
		    end
	    else
	      redirect_to book_path(@book.slug)
	    end
	end

	def destroy
		@review= Review.find(params[:id])
		@destroy_id = @review.id
	    @book = @review.book
	    @review.destroy
	    respond_to do |format|
	      format.html { redirect_to post_path(@book.slug) }
	      format.js
	    end
	end

	private
    def review_params
      params.require(:review).permit(:content, :book_id)
    end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/admin/reviews/index.html.erb
<% provide(:title, "HTube | Admin") %>

<% content_for :back_end_main do %>
	<div class="right_col" role="main">
 
	    <div class="">
	        <div class="page-title">
	            <div class="title_left">
	                <h3>
	                    Reviews
	                </h3>
	            </div>
	        </div>
	        <div class="clearfix"></div>
	 
	        <div class="row">
	            <div class="col-sm-12">
	                <div class="x_panel">
	                    <div class="x_title">
	                        <h2>All reviews</h2>
	                        <ul class="nav navbar-right panel_toolbox">
	                            <li class="pull-right"><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
	                        </ul>
	                        <div class="clearfix"></div>
	                    </div>
	                    <div class="x_content">
	                        <!-- content starts here -->
	                            <div class="x_content">
        						<!-- content starts here -->
						        <table class="table table-striped" id="list-item" cellspacing="0" width="100%">
							        <thead>
							            <tr>
							                <th>Content</th>
							                <th>Review User</th>
							                <th>Book</th>
							                <th width="140px">Created Time</th>
							            </tr>
							        </thead>
							        <tfoot>
							            <tr>
							                <th>Content</th>
							                <th>Review User</th>
							                <th>Book</th>
							                <th>Created Time</th>
							            </tr>
							        </tfoot>
							        <tbody style="text-transform: capitalize;">
							        	<% @reviews.each do |review|%>
									        <tr>
									        	<td>
									        		<a href="<%= admin_review_path(review) %>" class="text-success"><u><%=review.content.slice(0...50) %></u></a>
									        	</td>
									        	<td><%=review.user.username%></td>
									        	<td><%=review.book.title%></td>
									        	<td><%=review.created_at%></td>
									        </tr>
								        <% end %>
							        </tbody>
							    </table>
						        <!-- content ends here -->
						    </div>
	                        <!-- content ends here -->
	                    </div>
	                </div>
	            </div>
	        </div>
	    </div>
	</div>
<% end %>
<% content_for :add_js do %>
	<script type="text/javascript">
	    $(document).ready(function () {
	    	//DataTable
	    	$('#list-item').DataTable();
	    	$('a[data-target=".delete_comfirm"]').click(function(){
	    		$('a[data-method="delete"]').attr('href','/admin/categories/' + $(this).data('id'));
	    	})
	    	
	    	<% if flash[:notice] %>
				new PNotify({
	              	title: 'Success',
	              	text: '<%= flash[:notice] %>',
	              	type: 'success',
	              	delay: 2000,
	              	styling: 'bootstrap3'
	          	});
          	<% end %>
	    })
	</script>
<% end %>
<% extends_layout "admin/layouts/master" %>

app/views/admin/reviews/show.html.erb
<% provide(:title, "HTube | Admin") %>
<% content_for :back_end_main do %>
	<div class="right_col" role="main">
 
	    <div class="">
	        <div class="page-title">
	            <div class="title_left">
	                <h3>
	                    Reviews
	                </h3>
	            </div>
	        </div>
	        <div class="clearfix"></div>
	 
	        <div class="row">
	            <div class="col-sm-12">
					<div class="x_panel">
					    <div class="x_title">
					        <h2><%= @review.book.title %></h2>
					        <ul class="nav navbar-right panel_toolbox">
					            <li class="pull-right"><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
					        </ul>
					        <div class="clearfix"></div>
					    </div>
					    <div class="x_content" id="book_content">
					        <!-- content starts here -->
						    	<div class="row">
						    		<div class="col-sm-3">
							    		<div class="form-group img_preview">
								    		<label for="book_img">Bookjacket</label>
								    		<div class="img">
										        <img src="<%= @review.book.img_path.url.nil? ? '/img/demo.png' : @review.book.img_path.url %>" class="full_width book_img img-thumbnail">
								        	</div>
									    </div>
							        </div>
						    		<div class="col-sm-9">
						    			<div class="form-group">
										    <h4>Title</h4>
										    <h3><%= @review.book.title%></h3>
										</div>
						    			<div class="form-group">
										    <h4>Reviews User</h4>
										    <h3><%= @review.user.username %></h3>
										</div>	
						    			<div class="form-group">
										    <h4>Content</h4>
										    <pre style="white-space: pre-line;font-family: inherit;padding: 0;font-size: inherit;word-break: break-word;background-color: #fff;border: none;margin: 0;">
										    	<%= @review.content %>
										    	
										    </pre>
										</div>
						    			<div class="form-group">
						    				<a type="button" class="btn btn-danger pull-right" data-toggle="modal" data-target=".delete_comfirm"><i class="fa fa-trash"></i> Delete</a>
										</div>
						    		</div>
						    	</div>
					        <!-- content ends here -->
					    </div>
					</div>
					<!-- MODAL DELETE CONFIRM -->
					<div class="modal fade delete_comfirm" tabindex="-1" role="dialog" aria-hidden="true">
					  <div class="modal-dialog modal-sm">
					    <div class="modal-content">

					      <div class="modal-header">
					        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span>
					        </button>
					        <h4 class="modal-title" id="myModalLabel2">Are you sure delete this?</h4>
					      </div>
					      <div class="modal-body text-center">
					        <button type="button" class="btn btn-default" data-dismiss="modal">No</button>
					        <a href="<%= admin_review_path(@review.id) %>" type="button" class="btn btn-success" data-method="delete">Yes, I'm sure</a>
					      </div>

					    </div>
					  </div>
					</div><!-- END MODAL -->
	            </div>
	        </div>
	    </div>
	</div>
<% end %>

<% content_for :add_js do %>
<% end %>

<% extends_layout "admin/layouts/master" %>