config/routes.rb
Rails.application.routes.draw do

  post '/rate' => 'rater#create', :as => 'rate'
  root 'front_end#index'

  get 'admin' => 'admin/users#index'
  namespace :admin do
    resources :books, path: 'books'
    resources :categories, path: 'categories'
    resources :tags, path: 'tags'
    resources :posts, path: 'posts'
    resources :users, path: 'users', only: [:index, :create, :show, :edit, :update, :destroy]
    resources :reviews, path: 'reviews', only: [:index, :show, :destroy]
  end

  get '/sign-up' => 'admin/users#new'
  get '/sign-in' => 'sessions#view_sign_in'
  post '/sign-in' => 'sessions#create'
  get '/sign-out' => 'sessions#destroy'
  
  # get 'post/:slug' => 'front_end#show_item', as: 'post'
  get 'category/:slug' => 'front_end#category', as: 'category'
  get 'tag/:slug' => 'front_end#tag', as: 'tag'
  get 'books/:slug' => 'front_end#show_book', as: 'book'
  get 'books' => 'front_end#all_book', as: 'books'
  get 'book/autocomplete' => 'front_end#autocomplete', as: 'autocomplete'
  get 'book/search_book' => 'front_end#search_book', as: 'search_book'
  post 'book/check_in_book' => 'front_end#check_in_book', as: 'check_in_book'

  # get 'profile' => 'user#show_user', as: 'profile_user'
  # post 'profile/update' => 'user#update_user', as: 'profile_user_update'

  resources :users ,param: :username do
    member do
      get 'read_books'
    end
  end
  resources :comments, only: [:create, :destroy]
  resources :reviews, only: [:create, :destroy, :update]
  # resources :books, only: [:index, :show]
end

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessor :remember_token

  enum role: [:User, :Administrator]

	has_many :posts
  has_many :reviews
  has_many :comments
  has_many :books
  has_many :books, :through => :user_book
	has_many :user_book, dependent: :destroy
	
	validates :username, presence: true, uniqueness: true, length: { maximum: 50}
	validates :email, presence: true, uniqueness: true
  mount_uploader :avatar, AvatarUploader
	has_secure_password
	validates :password, presence: true, length: { minimum: 6 }, allow_blank: true
  ratyrate_rater
  def self.get_all_users
    self.all
  end

  def self.get_user(user_id)
    self.find(user_id)
  end

  def self.create_user(data_create)
    user = self.new(data_create)
    user.role = 'User'
    user.save
    return user
  end

  def self.update_user(user_id,data_update)
    user = self.find(user_id)
    user.update(data_update)

    return user
  end
  
  def reviewed?(book_id)
    Review.find_by({ :book_id => book_id , :user_id => self.id})
  end
  
  def read_book?(book_id)
    UserBook.find_by({ :book_id => book_id , :user_id => self.id})
  end

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
  	return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end
  def is_admin?
    role == "Administrator" ? true : false
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
	before_action :signed_in_user, only: [:index,:show,:update]
	before_action :check_role

	def index
		@users = User.get_all_users
	end

	def new
		@user = User.new
	end

	def show
		user_id = params['id']
		@user = User.get_user(user_id)
	end

	def create
		@user = User.create_user(user_create_params)
		if !@user.errors.any?
			flash[:danger] = "Please sign in"
			redirect_to sign_in_path
		else
			render 'new'
		end
	end

	def update
		user_id = params['id']
		@user = User.update_user(user_id,user_update_params)
		if !@user.errors.any?
			flash[:success] = "Profile successfully updated"
			redirect_to :back
		else
			render 'show'
		end
	end

	private
		def user_create_params
			params.require(:user).permit(:username,:email,:password,:password_confirmation)
		end

		def user_update_params
			params.require(:user).permit(:fullname,:email,:password,:role,:address)
		end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
	def show
		@user = User.find_by(username: params[:username])
		# abort @user.inspect
	end

  	def edit
  		@user = User.find_by(username: params[:username])
  		if signed_in? and @user.id != current_user.id
	  		redirect_to root_path
	  	end
  	end

  	def update
  		if current_user.update_attributes(user_update_params)
  			flash[:alert] = "profile updated"
  			redirect_to :back
  		else
  			flash[:alert] = "profile not updated"
  		end
  	end
  	
  	def read_books
  		@user = User.find_by(username: params[:username])
  		@books = @user.books
  	end
  	private
		def user_update_params
			params.require(:user).permit(:avatar,:fullname,:address)
		end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_nav.html.erb
<nav class="bh_nav col-sm-3">
	<h3>Thông tin tài khoản</h3>
	<ul>
		<li><a href="<%= user_path(@user.username) %>">Thông tin chung</a></li>
		<% if @user.id == current_user.id %>
    		<li><a href="<%= edit_user_path(@user.username) %>">Cập nhật thông tin cá nhân</a></li>
		<% end %>
		<li><a href="<%= read_books_user_path(@user.username) %>">Sách đã đọc</a></li>
	</ul>
</nav>

app/views/users/edit.html.erb
<% provide(:title, @user.username) %>

<% content_for :front_end_main do %>

	<% if flash.alert %>
		<br>
  		<div class="alert alert-block alert-info">
  			<%= flash.alert %>
    		<button type="button" class="close" data-dismiss="alert">×
  		</div>
	<% end %>

	<%= render 'users/nav' %>
	
	<div class="col-sm-9" id="user_main_content">
		<div class="row">
		<%= form_for @user, html:{:class => 'form-horizontal'} do |f|%>
		    
			<div class="col-sm-2 col-sm-offset-1">
				<center class="form-group img_preview">
			    	<div class="img">
					    <img id="avatar_photo" src="<%= current_user.avatar.url %>" class="full_width book_img img-thumbnail">
					    <br><br>
				        <label class="btn btn-default" style="color: gray;">Upload Avatar
							<input type="file" style="display: none;" class="file-loading" name="user[avatar]" accept="image/*" onchange="readURL(this);">
							<%= f.file_field :avatar, class: 'hide file-loading', accept: 'image/*', onchange: 'readURL(this)'%>
				        </label>
			        </div>
				</center>
			</div>
			<div class="col-sm-7 col-sm-offset-0">
					<input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
				  	<div class="form-group">
				    	<label for="gender" class="col-sm-3 control-label">User name</label>
				    	<div class="col-sm-9">
					      	<input type="text" class="form-control" id="gender" value="<%= @user.username %>" disabled>
					    </div>
				  	</div>
				  	<div class="form-group">
				    	<label for="email" class="col-sm-3 control-label">Email</label>
				    	<div class="col-sm-9">
					      	<input type="email" class="form-control" id="email" value="<%= @user.email %>" disabled>
					    </div>
				  	</div>
				  	<div class="form-group">
				    	<label for="fullname" class="col-sm-3 control-label">Full name</label>
				    	<div class="col-sm-9">
					      	<input type="text" class="form-control" id="fullname" value="<%= @user.fullname %>" name="user[fullname]">
					    </div>
				  	</div>
				  	<div class="form-group">
				    	<label for="address" class="col-sm-3 control-label">Address</label>
				    	<div class="col-sm-9">
					      	<input type="text" class="form-control" id="address" value="<%= @user.address %>" name="user[address]">
					    </div>
				  	</div>
				  	<div class="form-group">
				    	<div class="col-sm-offset-3 col-sm-9">
				      		<button type="submit" class="btn btn-primary" style="background-color:#05b2e9;border-color:#05b2e9">Update</button>
				    	</div>
				  	</div>	
			</div>
		<% end %>
		</div>
	</div>
<% end %>

<% content_for :add_js do %>
	<script type="text/javascript">
        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $('#avatar_photo').attr('src', e.target.result);
                }
                reader.readAsDataURL(input.files[0]);
            }
        }
    </script>
<% end %>

<% extends_layout "front_end/layouts/master" %>

app/views/users/read_books.html.erb
<% provide(:title, @user.username) %>

<% content_for :front_end_main do %>

	<% if flash.alert %>
		<br>
  		<div class="alert alert-block alert-info">
  			<%= flash.alert %>
    		<button type="button" class="close" data-dismiss="alert">×
  		</div>
	<% end %>

	<%= render 'users/nav' %>
	
	<div class="col-sm-9" id="user_main_content">
	    <% if @books.empty? %>
	        Không có sách nào để hiển thị
	    <% else %>
    		<table class="table table-hover">
                <thead>
                    <tr>
                        <th>Bìa</th>
                        <th>Tên sách</th>
                        <th>Tác giả</th>
                    </tr>
                </thead>
                <tbody>
                    <% @books.each do |book| %>
                    <tr>
                        <td><a href="<%= book_path(book.slug) %>"><img src="<%= book.img_path.thumb.url %>"></a></td>
                        <td><a href="<%= book_path(book.slug) %>"><%= book.title %></a></td>
                        <td><%= book.author %></td>
                    </tr>
                    <% end %>
                </tbody>
            </table>
        <% end %>
	</div>
<% end %>

<% extends_layout "front_end/layouts/master" %>

app/views/users/show.html.erb
<% provide(:title, @user.username) %>

<% content_for :front_end_main do %>

	<% if flash.alert %>
		<br>
  		<div class="alert alert-block alert-info">
  			<%= flash.alert %>
    		<button type="button" class="close" data-dismiss="alert">×
  		</div>
	<% end %>

	<%= render 'users/nav' %>
	
	<div class="col-sm-9" id="user_main_content">
		<div class="row">
			<div class="col-sm-2 col-sm-offset-1">
				<center class="form-group img_preview">
			    	<div class="img">
					    <img id="avatar_photo" src="<%= @user.avatar.url %>" class="full_width book_img img-thumbnail">
			        </div>
				</center>
			</div>
			<div class="col-sm-7 col-sm-offset-0">
			    <% if @user.id == current_user.id %>
			        <div>
    			        <label class="col-sm-4">User name</label>
    			        <div class="col-sm-8">
    				        <p><%= @user.username %></p>
    				    </div>
			        </div>
			    <% end %>
		        <div>
			        <label class="col-sm-4">Email</label>
			        <div class="col-sm-8">
				        <p><%= @user.email %></p>
				    </div>
		        </div>
		        <% if @user.fullname != '' && !@user.fullname.nil? %>
    		        <div>
    			        <label class="col-sm-4">Full name</label>
    			        <div class="col-sm-8">
    				        <p><%= @user.fullname %></p>
    				    </div>
    		        </div>
		        <% end %>
		        <% if @user.address != '' && !@user.address.nil? %>
    		        <div>
    			        <label class="col-sm-4">Address</label>
    			        <div class="col-sm-8">
    				        <p><%= @user.address %></p>
    				    </div>
    		        </div>
		        <% end %>
			  	<% if @user.id == current_user.id %>
    			  	<div class="form-group">
    			    	<div class="col-sm-3">
    			      		<a href="<%= edit_user_path(current_user.username) %>" class="btn btn-primary" style="background-color:#05b2e9;border-color:#05b2e9"><i class="fa fa-edit"></i> Edit</a>
    			    	</div>
    			  	</div>
			  	<% end %>
			</div>
		</div>
	</div>
<% end %>

<% extends_layout "front_end/layouts/master" %>