config/routes.rb
Rails.application.routes.draw do

  post '/rate' => 'rater#create', :as => 'rate'
  root 'front_end#index'

  get 'admin' => 'admin/users#index'
  namespace :admin do
    resources :books, path: 'books'
    resources :categories, path: 'categories'
    resources :tags, path: 'tags'
    resources :posts, path: 'posts'
    resources :users, path: 'users', only: [:index, :create, :show, :edit, :update, :destroy]
    resources :reviews, path: 'reviews', only: [:index, :show, :destroy]
  end

  get '/sign-up' => 'admin/users#new'
  get '/sign-in' => 'sessions#view_sign_in'
  post '/sign-in' => 'sessions#create'
  get '/sign-out' => 'sessions#destroy'
  
  # get 'post/:slug' => 'front_end#show_item', as: 'post'
  get 'category/:slug' => 'front_end#category', as: 'category'
  get 'tag/:slug' => 'front_end#tag', as: 'tag'
  get 'books/:slug' => 'front_end#show_book', as: 'book'
  get 'books' => 'front_end#all_book', as: 'books'
  get 'book/autocomplete' => 'front_end#autocomplete', as: 'autocomplete'
  get 'book/search_book' => 'front_end#search_book', as: 'search_book'
  post 'book/check_in_book' => 'front_end#check_in_book', as: 'check_in_book'

  # get 'profile' => 'user#show_user', as: 'profile_user'
  # post 'profile/update' => 'user#update_user', as: 'profile_user_update'

  resources :users ,param: :username do
    member do
      get 'read_books'
    end
  end
  resources :comments, only: [:create, :destroy]
  resources :reviews, only: [:create, :destroy, :update]
  # resources :books, only: [:index, :show]
end

app/controllers/front_end_controller.rb
class FrontEndController < ApplicationController
  before_action :generate_categories

  def index
    # @posts = custom_paginate(Post.all)
    @newest_books = Book.get_books(4)
  end

  def category
  	category = Category.get_category_by_slug(params[:slug])
  	# @books = custom_paginate(category.books)
    @books = category.books
    @category = category.category
    @category_id = category.id
  	render 'list_books'
  end

  def tag
    tag = Tag.find_by(slug: params[:slug])
    @posts = custom_paginate(tag.posts)
    render 'index'
  end

  def show_book
    book_slug = params[:slug]
    @book = Book.get_book_by_slug(book_slug)
    @categories = @book.categories
    @book = Book.find_by(slug: params[:slug])
    if signed_in?
      @review = current_user.reviews.build
    end
    @reviews = @book.reviews.paginate(page: params[:page])
    render 'show_book'
  end

  def all_book
    @books = Book.get_all_books()
    @category = 'Tất cả các sách'
    render 'list_books'
  end

  def search_book
  	@books = Book.search_title(params[:query])
  	unless params[:category].nil?
    	if params[:category] != ''
    	  @books = Book.joins("JOIN categories_books ON categories_books.book_id = books.id AND categories_books.category_id = " + params[:category]).where('title LIKE ?', "%#{params[:query]}%")
    	end
  	end
    @category = 'Danh sách tìm kiếm'
    render 'list_books'
  end
  
  def check_in_book
    if params[:type] == 'create'
      UserBook.create('user_id'=>current_user.id , 'book_id'=>params[:book_id])
    else
      userbook = UserBook.find_by({ :book_id => params[:book_id] , :user_id => current_user.id})
      userbook.delete
    end
    @check_in_book_type = params[:type]
    respond_to do |format|
      format.js { render 'front_end/js/check_in_book' }
    end
  end

  def autocomplete
    books = Book.search_title(params[:query])
    results = books.map { |e| {:title => e.title,:url => book_path(e.slug) , :thumb_img => e.img_path.thumb.url} }
    render json: results
    # render json: Book.search(params[:query], autocomplete: true, limit: 10).map(&:title)
  end

  private
  	
    def custom_paginate(items)
      items.paginate(:page => params[:page], :per_page => 2)
    end
end

app/helpers/front_end_helper.rb
module FrontEndHelper
end

app/views/front_end/_footer.html.erb
<footer class="footer_height container-fluid">
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                        <div class="row">
                            <div class="col-md-3 footer-nav">
                                <h4 class="hidden-xs hidden-sm">Hỗ trợ khách hàng</h4>
                                <ul>
                        
                                    <li class="footer-link-mobile first">
                                        <a rel="nofollow" href="http://hotro.tiki.vn/hc/vi" target="_blank" title="Các câu hỏi thường gặp">Các câu hỏi thường gặp</a>
                                    </li>
                                    <li class="hidden-xs hidden-sm">
                                        <a rel="nofollow" href="http://hotro.tiki.vn/hc/vi/requests/new" target="_blank" title="Email">Gửi yêu cầu hỗ trợ</a>
                                    </li>
                                    <li class="footer-link-mobile">
                                        <a rel="nofollow" href="http://hotro.tiki.vn/hc/vi/categories/200126644" target="_blank" title="Hướng dẫn đặt hàng">Hướng dẫn đặt hàng</a>
                                    </li>
                                    <li class="footer-link-mobile">
                                        <a rel="nofollow" href="http://hotro.tiki.vn/hc/vi/categories/200123960" target="_blank" title="Phương thức vận chuyển">Phương thức vận chuyển</a>
                                    </li>
                                    <li class="footer-link-mobile last">
                                        <a rel="nofollow" href="/doi-tra-de-dang" target="_blank" title="Chính sách đổi trả hàng">Chính sách đổi trả</a>
                                    </li>
                                </ul>
                            </div>
                            <div class="col-md-3 footer-nav footer-account" id="footer-account">
                                <h4>Tài khoản của bạn</h4>
                                <ul>
                                    <li>
                                        <a rel="nofollow" href="#" data-toggle="modal" data-target="#login-form" title="Đăng nhập">Đăng nhập</a>
                                    </li>
                                    <li>
                                        <a rel="nofollow" href="#" data-toggle="modal" data-target="#register-form" title="Đăng ký">Đăng ký</a>
                                    </li>
                                </ul>
                            </div>
    
                            <div class="col-md-3 footer-nav hidden-xs hidden-sm">
                                <h4>Về Tiki.vn</h4>
                                <ul>
                                    <li>
                                        <a target="_blank" rel="nofollow" href="/gioi-thieu-ve-tiki" title="Giới thiệu Tiki.vn">Giới thiệu Tiki.vn</a>
                                    </li>
                                    <li>
                                        <a rel="nofollow" href="" target="_blank" title="Tuyển dụng">Tuyển Dụng</a>
                                    </li>
                                    <li>
                                        <a rel="nofollow" href="" target="_blank" title="Chính sách bảo mật">Chính sách bảo mật</a>
                                    </li>
                                    <li>
                                        <a rel="nofollow" href="" target="_blank" title="Điều khoản sử dụng">Điều khoản sử dụng</a>
                                    </li>
                                    <li>
                                        <a rel="nofollow" href="" target="_blank" title="Hội Sách">Hội Sách Online</a>
                                    </li>
                                    <li>
                                        <a rel="nofollow" href="" target="_blank" title="Giới thiệu Tiki Xu">Giới thiệu Tiki Xu</a>
                                    </li>
                                    <li>
                                        <a rel="nofollow" href="/tu-van" target="_blank" title="Tiki Tư Vấn">Tiki Tư Vấn</a>
                                    </li>
                                    <li>
                                        <a rel="nofollow" href="/sach-b2b" target="_blank" title="Ưu đãi doanh nghiệp">Ưu đãi doanh nghiệp</a>
                                    </li>
                                </ul>
                            </div>
    
                            <div class="col-md-3 footer-nav hidden-xs hidden-sm">
                                <h4>Hợp tác & Liên kết</h4>
                                <ul>
                                    <li>
                                        <a title="Quy chế hoạt động Sàn giao dịch TMĐT của Tiki.vn" rel="nofollow" href="/quy-che-hoat-dong-sgdtmdt" target="_blank">Quy chế hoạt động Sàn GDTMĐT</a>
                                    </li>
                                    <li>
                                        <a title="Ăn gì ở đâu" rel="nofollow" href="" target="_blank">Foody.vn - Ăn gì ở đâu</a>
                                    </li>
                                    <li>
                                        <a title="Đặt khách sạn giá rẻ" rel="nofollow" href="#" target="_blank">iVIVU.com - Đặt khách sạn giá rẻ </a>
                                    </li>
                                </ul>
                            </div>
    
                        </div>
                    </div>
            <div class="col-md-4">
                        <h4>Contact us</h4>
                        <form class="">
                          <div class="">
                            <div class="form-group">
                                <div class="input-group">
                                    <div class="input-group-addon"><i class="fa fa-user"></i></div>
                                    <input type="text" class="form-control" id="login_username" placeholder="Username">
                                </div>
                                <span class="help-block has-error" id="email-error"></span>
                                </div>
                                <div class="form-group">
                                    <div class="input-group">
                                        <div class="input-group-addon"><i class="fa fa-at"></i></div>
                                        <input type="text" class="form-control" id="remail" placeholder="Email">
                                    </div>
                                    <span class="help-block has-error" data-error='0' id="remail-error"></span>
                                </div>
                            <textarea name="message" class="form-control" type="text" id="input-message" placeholder="Message"></textarea>
                          </div>  
                          <input type="submit" value="Submit" class="button_footer btn btn-primary" id="input-submit">
                        </form>
                    </div>
        </div>
    </div>
            
</footer>

app/views/front_end/_header.html.erb
<header class="container main_header">
	<div class="row">
		<div class="col-sm-3 text-center">
			<a href="<%= root_path %>">
				<a href="/"><img src="/img/avatar.jpg" style="display:inline-block" height=69></a>
			</a>
		</div>
		<div class="col-sm-6 search">
			<%= form_tag(search_book_path, method: "GET") do %>
				<input type="text" name="query" placeholder="Search" id="book_search" />
				<button type="submit">TÌM</button>
			<% end %>
		</div>
		<div class="col-sm-3 login">
			<div class="pull-left hidden-sm" style="margin-right:20px">
				<% if signed_in? %>
				<img src="<%= current_user.avatar.thumb.url %>" width="40" height="40">
				<% end %>
			</div>
			<div style="padding-top:11px" class="pull-left">
				<% if signed_in? %>
					<div class="dropdown">
						<a id="dLabel" class="text-capitalize" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="cursor: pointer;">
						    Hello <%= current_user.username %>
						    <span class="caret"></span>
						</a>
						<ul class="dropdown-menu" aria-labelledby="dLabel">
						    <li><a href="<%= edit_user_path(current_user.username) %>" class="text-capitalize">Trang cá nhân</a></li>
						    <% if current_user.is_admin? %>
						    	<li><a href="<%= admin_path %>" data-no-turbolink>Bảng điều khiển</a></li>
						    <% end %>
						    <li><a href="<%= sign_out_path %>">Đăng xuất</a></li>
						</ul>
					</div>
				<% else %>
					<a href="<%= sign_in_path %>" data-no-turbolink>Đăng nhập</a> |
					<a href="<%= sign_up_path %>" data-no-turbolink>Đăng ký</a>
				<% end %>
			</div>
			<div class="clearfix"></div>
		</div>
	</div>
</header>
<div class="container-fluid" style="border-top:1px solid #ddd;border-bottom:1px solid #ddd">
	<div class="container">
		<ol class="breadcrumb breadcrumb_top">
		  <li><a href="<%= root_path %>">Trang chủ</a></li>
		  <li class="active">Data</li>
		</ol>
	</div>
</div>

app/views/front_end/_menu.html.erb
<nav class="bh_nav col-sm-3">
	<h3>Danh muc</h3>
	<ul>
		<li><a href="<%= books_path %>">Tất cả đầu sách</li>
		<% @categories.each do |category| %>
			<li><a href="<%= category_path(category.slug) %>"><%= category.category %></a>	</li>
		<% end %>
	</ul>
</nav>

app/views/front_end/index.html.erb
<% provide(:title, "Tiki | Home") %>

<% content_for :add_css do %>
	<!-- <link rel="stylesheet" type="text/css" href="/css/swiper.min.css"> -->
<% end %>

<% content_for :front_end_main do %>
	<%= render 'front_end/menu' %>
	<div class="col-sm-9" id="index_main_content">
	    <!--<div class="row">-->
	    <!--	<div class="col-sm-12 row_title_container">-->
	    <!--		<div class="row_title">-->
		   <!-- 		<h3 class="pull-left">TOP sách được bình chọn</h3>-->
		   <!-- 		<a href="" class="text-right pull-right">-->
		   <!-- 			<u><i class="fa fa-hand-o-right"></i> Xem thêm</u>-->
	    <!--			</a>-->
		   <!-- 		<div class="clearfix"></div>-->
	    <!--		</div>-->
	    <!--	</div>-->
	    <!--	<div class="col-sm-3 col-xs-6">-->
	    <!--		<img src="/img/demo.png" class="full_width">-->
	    <!--	</div>-->
	    <!--	<div class="col-sm-3 col-xs-6">-->
	    <!--		<img src="/img/demo.png" class="full_width">-->
	    <!--	</div>-->
	    <!--	<div class="col-sm-3 col-xs-6">-->
	    <!--		<img src="/img/demo.png" class="full_width">-->
	    <!--	</div>-->
	    <!--	<div class="col-sm-3 col-xs-6">-->
	    <!--		<img src="/img/demo.png" class="full_width">-->
	    <!--	</div>-->
	    <!--</div>-->
	    <% if @newest_books.count > 0 %>
		    <div class="row">
		    	<div class="col-sm-12 row_title_container">
		    		<div class="row_title">
			    		<h3 class="pull-left">Sách mới nhất</h3>
			    		<a href="<%= books_path %>" class="text-right pull-right">
			    			<u><i class="fa fa-hand-o-right"></i> Xem thêm</u>
		    			</a>
			    		<div class="clearfix"></div>
		    		</div>
		    	</div>
		    	<% @newest_books.each do |book| %>
			    	<div class="col-sm-3 col-xs-6">
			    		<a href="<%= book_path(book.slug) %>" style="display:block">
				    		<img src="<%= book.img_path.url %>" class="full_width" height="290">
				    	</a>
				    	<a href="<%= book_path(book.slug) %>">
				    		<h5><%= book.title %></h5>
			    		</a>
			    	</div>
		    	<% end %>
		    </div>
	    <% end %>
	</div>
<% end %>

<% content_for :add_js do %>
	<!-- <script type="text/javascript" src="/js/swiper.jquery.min.js"></script>
	<script type="text/javascript">
		var swiper = new Swiper('.swiper-container', {
	        slidesPerView: 4,
	        nextButton: '.swiper-button-next',
	        prevButton: '.swiper-button-prev',
	        spaceBetween: 20
	    });
	</script> -->
<% end %>

<% extends_layout "front_end/layouts/master" %>

app/views/front_end/list_books.html.erb
<% provide(:title, "Tiki | Home") %>

<% content_for :add_css do %>
	<!-- <link rel="stylesheet" type="text/css" href="/css/swiper.min.css"> -->
<% end %>

<% content_for :front_end_main do %>
	<%= render 'front_end/menu' %>
	<div class="col-sm-9" id="list_books_main_content">
	    <div class="row">
	    	<div class="col-sm-12 row_title_container">
	    		<div class="row_title">
		    		<h3 class="pull-left"><%= @category %></h3>
		    		<% unless @category_id.nil? %>
						<%= form_tag(search_book_path, method: "GET", class: 'pull-right') do %>
							<input type="hidden" name="category" value="<%= @category_id %>" />
							<input type="text" name="query" placeholder="Search" id="book_search" />
							<button type="submit">Tìm kiếm</button>
						<% end %>
					<% end %>
		    		<div class="clearfix"></div>
	    		</div>
	    	</div>
	    	<% @books.each do |book| %>
		    	<div class="col-sm-3">
		    		<div>
			    		<a href="<%= book_path(book.slug) %>" style="display: block;">
				    		<img src="<%= book.img_path.url %>" class="full_width" height="290">
			    		</a>
			    		<a href="<%= book_path(book.slug) %>">
				    		<h5><%= book.title %></h5>
				    		<h5><%= book.author %></h5>
			    		</a>
		    		</div>
		    	</div>
	    	<% end %>
	    </div>
	</div>
<% end %>

<% extends_layout "front_end/layouts/master" %>

app/views/front_end/show_book.html.erb
<% provide(:title, @book.title) %>

<% content_for :add_css do %>
	<!-- <link rel="stylesheet" type="text/css" href="/css/swiper.min.css"> -->
<% end %>

<% content_for :front_end_main do %>
	<div class="col-sm-12" id="show_book_main_content">
	    <div class="row">
	    	<div class="col-sm-5 book_img text-center">
	    		<img src="<%= @book.img_path.url %>" width="290">
	    	</div>
	    	<div class="col-sm-7">
	    		<h3 class="text-capitalize"><%= @book.title %></h3>
	    		<p>Tác giả : <strong class="text-primary text-capitalize"><%= @book.author %></strong></p>
	    		<p class="list_categories">Chuyên mục<strong class="text-primary">
		    		<% @categories.each do |category| %>
		    			<a href="<%= category_path(category.slug) %>"><%= category.category %></a>
		    		<% end %>
	    		</strong></p>
		    	<div>
		    		<%= rating_for @book, 'quality', star: 5, disable_after_rate: false, enable_half: true,cancel_place: 'right' %>
			    		
				   	<% unless signed_in? %>
		    			<div>
		    				<a class="rate" href="#" data-toggle="modal" data-target=".modal"></a>
		    			</div>
				    <% end %>
		    	</div>
	    		<% unless @book.rates("quality").nil? %>
					(<%= @book.rates("quality").count %> ratings)
				<% end %>
				<p>
					<br>
					<iframe src="https://www.facebook.com/plugins/share_button.php?href=<%= request.original_url %>&layout=button&mobile_iframe=true&width=59&height=20&appId" width="70" height="20" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true"></iframe>
					<iframe src="https://platform.twitter.com/widgets/tweet_button.html?size=i&url=<%= request.original_url %>&related=twitterapi%2Ctwitter" width="80" height="20" style="border: none; overflow: hidden;" scrolling="no" frameborder="0" allowTransparency="true"></iframe>
				</p>
				<% if signed_in? %>
					<%= form_tag(check_in_book_path, remote: true,id: 'check_in_book_form') do |f|%>
						Bạn đã đọc sách này chưa? 
						<%= hidden_field_tag(:book_id, @book.id) %>
						<% unless current_user.read_book?(@book.id)%>
							<%= hidden_field_tag(:type, 'create') %>
							<button type="submit" class="btn btn-default btn-xs" id="check_in_book_create"><i class="glyphicon glyphicon-hand-right"></i> Check in ngay</button>
						<% else %>
							<%= hidden_field_tag(:type, 'delete') %>
							<button type="submit" class="btn btn-default btn-xs" id="check_in_book_delete"><i class="glyphicon glyphicon-ok"></i> Đã đọc</button>
						<% end %>
						<i class="fa fa-spinner fa-spin fa-fw" style="display:none"></i>
					<% end %>
				<% end %>
	    		<div class="book_description">
	    			<h4>Gioi thieu sach</h4>
	    			<pre>
	    				<%= @book.description %>
	    			</pre>
	    		</div>
	    	</div>
	    </div>

	    <div class="row book_comment">
	    	<h4>Để lại lời nhận xét của bạn</h4>
	    	<div class="text-left">
	    		<% if signed_in? %>
	    			<% unless current_user.reviewed?( @book.id ) %>
			    		<%= form_for(@review, remote: true) do |f| %>
							<div class="field">
								<%= f.text_area :content, placeholder: "Để lại lời nhận xét ...", id: 'review_content', class: "full_width", required: "",'data-autoresize':'', 'spellcheck': false %>
								<div><%= hidden_field_tag :book_id, @book.id %></div>
							</div>
							<%= f.submit "Gửi lời nhận xét của bạn", class: "btn btn-primary" , id: 'review_submit' %>
						<% end %>
					<% else %>
						<%= form_for(@review, remote: true) do |f| %>
							<div class="field">
								<%= f.text_area :content, placeholder: "Để lại lời nhận xét ...", id: 'review_content', class: "full_width", required: "" , disabled: ""%>
								<div><%= hidden_field_tag :book_id, @book.id %></div>
							</div>
							<%= f.submit "Gửi lời nhận xét của bạn", class: "btn btn-primary" , id: 'review_submit' , disabled: ''%>
						<% end %>
					<% end %>
				<% else %>
					<textarea class="full_width"  placeholder="Để lại lời nhận xét ..."></textarea>
					<input type="submit" class="btn btn-primary" value="Gửi lời nhận xét của bạn" data-toggle="modal" data-target=".modal"/>
				<% end %>
	    	</div>
	    	<ul class="list_reviews">
			    <% if @book.reviews.any? %>
			        <%= render @reviews %>
			      	<%= will_paginate @reviews %>
			    <% end %>
	    	</ul>
	    </div>
	</div>
	<!-- MODAL -->
	<div class="modal fade" tabindex="-1" role="dialog">
	  <div class="modal-dialog" role="document">
	    <div class="modal-content">
	      <div class="modal-header">
	        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
	        <h4 class="modal-title">Thông báo</h4>
	      </div>
	      <div class="modal-body">
	        <p>Bạn phải đăng nhập để sử dụng chức năng này</p>
	        <p><a href="<%= sign_in_path %>" data-no-turbolink>Đăng nhập</a> ngay</p>
	      </div>
	      <div class="modal-footer text-center">
	        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
	      </div>
	    </div><!-- /.modal-content -->
	  </div><!-- /.modal-dialog -->
	</div><!-- /.modal -->
<% end %>

<% content_for :add_js do %>
	<script type="text/javascript">
		
	</script>
<% end %>

<% extends_layout "front_end/layouts/master" %>

app/views/front_end/show_user.html.erb
<% provide(:title, @user.username) %>

<% content_for :front_end_main do %>

	<% if flash.alert %>
		<br>
  		<div class="alert alert-block alert-info">
  			<%= flash.alert %>
    		<button type="button" class="close" data-dismiss="alert">×
  		</div>
	<% end %>

	<nav class="bh_nav col-sm-3">
		<h3>Thông tin tài khoản</h3>
		<ul>
			<li><a href="">Thông tin chung</a></li>
			<li><a href="">Sách đã đọc</a></li>
		</ul>
	</nav>
	
	<div class="col-sm-9" id="user_main_content">
		<div class="row">
		<form class="form-horizontal" action="<%= profile_user_update_path %>" method="POST" enctype="multipart/form-data">
			<div class="col-sm-2 col-sm-offset-1">
				<center class="form-group img_preview">
			    	<div class="img">
					    <img id="avatar_photo" src="<%= current_user.avatar.url %>" class="full_width book_img img-thumbnail">
					    <br><br>
				        <label class="btn btn-default" style="color: gray;">Upload Avatar
							<input type="file" style="display: none;" class="file-loading" name="user[avatar]" accept="image/*" onchange="readURL(this);">
				        </label>
			        </div>
				</center>
			</div>
			<div class="col-sm-7 col-sm-offset-0">
					<input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
				  	<div class="form-group">
				    	<label for="gender" class="col-sm-3 control-label">User name</label>
				    	<div class="col-sm-9">
					      	<input type="text" class="form-control" id="gender" value="<%= @user.username %>" disabled>
					    </div>
				  	</div>
				  	<div class="form-group">
				    	<label for="email" class="col-sm-3 control-label">Email</label>
				    	<div class="col-sm-9">
					      	<input type="email" class="form-control" id="email" value="<%= @user.email %>" disabled>
					    </div>
				  	</div>
				  	<div class="form-group">
				    	<label for="fullname" class="col-sm-3 control-label">Full name</label>
				    	<div class="col-sm-9">
					      	<input type="text" class="form-control" id="fullname" value="<%= @user.fullname %>" name="user[fullname]">
					    </div>
				  	</div>
				  	<div class="form-group">
				    	<label for="address" class="col-sm-3 control-label">Address</label>
				    	<div class="col-sm-9">
					      	<input type="text" class="form-control" id="address" value="<%= @user.address %>" name="user[address]">
					    </div>
				  	</div>
				  	<div class="form-group">
				    	<div class="col-sm-offset-3 col-sm-9">
				      		<button type="submit" class="btn btn-primary" style="background-color:#05b2e9;border-color:#05b2e9">Update</button>
				    	</div>
				  	</div>	
			</div>
		</form>
		</div>
	</div>
<% end %>

<% content_for :add_js do %>
	<script type="text/javascript">
        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $('#avatar_photo').attr('src', e.target.result);
                }
                reader.readAsDataURL(input.files[0]);
            }
        }
    </script>
<% end %>

<% extends_layout "front_end/layouts/master" %>